import {
  ArrowRight,
  ArrowUp,
  ArrowUpRight,
  Award,
  BadgeCheck,
  CalendarDays,
  Check,
  ChevronLeft,
  ChevronRight,
  Cloud,
  Code2,
  Database,
  Download,
  ExternalLink,
  GitBranch,
  Layers,
  LoaderCircle,
  Mail,
  Menu,
  Mic,
  PenLine,
  Phone,
  Rocket,
  Server,
  Settings2,
  Shield,
  Sparkles,
  Terminal,
  TriangleAlert,
  Users,
  Wrench,
  X,
  Zap,
  type LucideIcon,
} from "lucide-react";

import type { IconName } from "@/types";

/**
 * The only place a lucide symbol is named, and only for interface glyphs.
 *
 * Data files choose a glyph by its `IconName`, which keeps the set closed and
 * means a content edit can never reach for an icon that is not bundled. Brand
 * marks are the separate `BrandIcon` path — see `lib/brand-icons.ts`.
 */
export const icons: Readonly<Record<IconName, LucideIcon>> = {
  mail: Mail,
  phone: Phone,
  download: Download,
  external: ExternalLink,
  "arrow-right": ArrowRight,
  "arrow-up": ArrowUp,
  "arrow-up-right": ArrowUpRight,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  menu: Menu,
  close: X,
  check: Check,
  loader: LoaderCircle,
  code: Code2,
  server: Server,
  sparkles: Sparkles,
  database: Database,
  cloud: Cloud,
  settings: Settings2,
  terminal: Terminal,
  wrench: Wrench,
  award: Award,
  certificate: BadgeCheck,
  mic: Mic,
  users: Users,
  "git-branch": GitBranch,
  layers: Layers,
  shield: Shield,
  zap: Zap,
  calendar: CalendarDays,
  rocket: Rocket,
  pen: PenLine,
  alert: TriangleAlert,
};
